#!/usr/bin/env python3
"""
sound_script.py — the recording brief for every sound in the game.

Same idea as the voice script: one row per slot, generated from SoundBank so it
cannot drift. The slot name is the field to paste an asset id into and the
filename to record it as.

Writes audio/SOUND_SCRIPT.md.
"""

import io, os, re

os.chdir(os.path.join(os.path.dirname(__file__), ".."))

src = io.open("src/shared/SoundBank.luau", encoding="utf-8").read()

# Each slot, with whatever prose comment sits above it — that comment is the
# brief, so it is pulled through rather than rewritten here.
def quoted(body, key):
    m = re.search(key + r'\s*=\s*"((?:[^"\\\\]|\\\\.)*)"', body)
    return m.group(1) if m else ""


def number(body, key):
    m = re.search(key + r"\s*=\s*([0-9.]+)", body)
    return m.group(1) if m else ""


def brief_above(before):
    """The prose immediately above a slot — that comment is the brief."""
    lines = before.rstrip().split("\n")
    i = len(lines) - 1
    while i >= 0 and lines[i].strip() == "":
        i -= 1
    out = []
    if i >= 0 and lines[i].strip() == "]]":
        i -= 1
        while i >= 0 and not lines[i].strip().startswith("--[["):
            out.insert(0, lines[i].strip())
            i -= 1
    else:
        while i >= 0 and lines[i].strip().startswith("--") and "──" not in lines[i]:
            out.insert(0, lines[i].strip().lstrip("-").strip())
            i -= 1
    return " ".join(w for w in out if w).strip()


slots = []
seen = set()
for m in re.finditer(r"SoundBank\.([A-Z_]+) = \{\n(.*?)\n\}", src, re.S):
    name, body = m.group(1), m.group(2)
    seen.add(name)
    slots.append({
        "name": name,
        "caption": quoted(body, "caption"),
        "id": quoted(body, "id"),
        "volume": number(body, "volume"),
        "speed": number(body, "speed"),
        "looped": re.search(r"looped\s*=\s*true", body) is not None,
        "note": brief_above(src[: m.start()]),
    })

for m in re.finditer(r"SoundBank\.([A-Z_]+) = \{ ([^\n}]+)\}", src):
    if m.group(1) in seen:
        continue
    seen.add(m.group(1))
    body = m.group(2)
    slots.append({
        "name": m.group(1),
        "caption": quoted(body, "caption"),
        "id": quoted(body, "id"),
        "volume": number(body, "volume"),
        "speed": number(body, "speed"),
        "looped": False,
        "note": brief_above(src[: m.start()]),
    })

slots.sort(key=lambda s: (not s["looped"], s["name"]))

md = [
    "# Sound script",
    "",
    "Generated by `tools/sound_script.py` from `src/shared/SoundBank.luau`.",
    "Do not edit by hand.",
    "",
    f"**{len(slots)} slots.**",
    "",
    "Every sound in the game is a named slot. Each one currently points at audio",
    "that ships inside the Roblox client, pitched and levelled into roughly the",
    "right shape — so the game is audible with no uploads and none of it is",
    "finished. Changing a slot's `id` swaps the real recording in and nothing",
    "else in the codebase changes, because no code knows what a file is called.",
    "",
    "The **slot name** is the filename to record it as and the field to paste the",
    "asset id into. The **caption** is what a player reading captions is told,",
    "which is also the tightest description of what the sound has to communicate.",
    "",
    "## How to hear what is there now",
    "",
    "In game, press **F9** → *Play every sound, named*. It plays all of them in",
    "turn with the slot name on screen. Some of the placeholders are certainly",
    "silent and some are certainly wrong; that is the way to find out which.",
    "",
    "## Levels",
    "",
    "The mix has one rule and the rest follows from it: **the hum is the floor of",
    "the mix, not a layer in it.** If a player consciously notices it during",
    "ordinary play it is 3 dB too loud. The startles are the only thing allowed to",
    "be loud, and they are loud because everything else is not.",
    "",
    "Peak ceiling −1.0 dBTP. A large startle sits about 18 LU above the bed. The",
    "transient carries the fright; a sustained roar just gets the headphones taken",
    "off, and this audience is largely teenagers at one in the morning.",
    "",
    "---",
    "",
    "## Loops — room tone",
    "",
    "These run continuously and are positioned in the world. They are the hardest",
    "to fake and the most valuable to get right: the game is navigated by them.",
    "",
]

def table(rows):
    out = ["| slot | caption | now | level |", "| --- | --- | --- | --- |"]
    for s in rows:
        placeholder = s["id"].replace("rbxasset://sounds/", "")
        vol = s["volume"]
        flag = " **(silent)**" if vol in ("0", "0.0") else ""
        out.append(f'| `{s["name"]}` | {s["caption"]} | `{placeholder}`{flag} | {vol} |')
    return out

md += table([s for s in slots if s["looped"]])
md += ["", "### What each loop needs", ""]
for s in slots:
    if s["looped"] and s["note"]:
        md.append(f'**{s["name"]}** — {s["note"]}')
        md.append("")

md += ["---", "", "## One-shots", "",
       "Events. Recorded close, dry, and trimmed hard at the top so the transient",
       "lands exactly on the frame the game plays it.", ""]
md += table([s for s in slots if not s["looped"]])
md += ["", "### What each one needs", ""]
for s in slots:
    if not s["looped"] and s["note"]:
        md.append(f'**{s["name"]}** — {s["note"]}')
        md.append("")

md += [
    "---",
    "",
    "## Uploading",
    "",
    "1. [create.roblox.com](https://create.roblox.com) → Creator Dashboard →",
    "   *Development Items* → *Audio* → *Add Audio*. Many files at once is fine.",
    "2. Copy each asset id from its item URL.",
    "3. In `src/shared/SoundBank.luau`, change that slot's `id` to",
    "   `rbxassetid://<the number>`.",
    "",
    "Sound effects clear moderation faster than speech. Anything over about six",
    "minutes will not upload; nothing here is close to that.",
    "",
]

io.open("audio/SOUND_SCRIPT.md", "w", encoding="utf-8").write("\n".join(md) + "\n")
print(f"{len(slots)} slots -> audio/SOUND_SCRIPT.md")
