#!/usr/bin/env python3
"""
stamp.py — write the current commit into the game.

"Are my changes in?" should never be a question anybody has to reason about.
This writes the commit the working tree is on into src/shared/Build.luau, which
the game prints on start and shows on screen for a few seconds when you join.

Run it before committing. tools/verify.sh runs it too.
"""

import io, os, subprocess, datetime

os.chdir(os.path.join(os.path.dirname(__file__), ".."))

def git(*args):
    return subprocess.run(["git", *args], capture_output=True, text=True).stdout.strip()

sha = git("rev-parse", "--short", "HEAD") or "unknown"
subject = git("log", "-1", "--format=%s") or "uncommitted"
when = git("log", "-1", "--format=%cd", "--date=format:%d %b %H:%M") or "—"
dirty = bool(git("status", "--porcelain", "--", "src", "default.project.json"))

def lua(text):
    """A Luau string literal. A commit subject can contain anything."""
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ") + '"'


body = f'''--!strict
--[[
	Build — which version of the game this is.

	Generated by tools/stamp.py. Do not edit; it is overwritten on every commit.

	This exists because "are my changes in?" is a question that should never
	need reasoning about. The answer is printed in the Output window on start
	and shown on screen for a few seconds when you join, and if it does not
	match what was just pushed then the sync is the problem and nothing else is.
]]

local Build = {{}}

Build.COMMIT = "{sha}"
Build.SUMMARY = {lua(subject)}
Build.WHEN = "{when}"
-- True when the working tree had uncommitted source changes at stamp time.
Build.DIRTY = {str(dirty).lower()}

function Build.line(): string
	return `Night Shift · {{Build.COMMIT}}{{if Build.DIRTY then "+" else ""}} · {{Build.WHEN}}`
end

return Build
'''

io.open("src/shared/Build.luau", "w", encoding="utf-8").write(body)
print(f"stamped {sha}{'+' if dirty else ''} — {subject}")
