#!/usr/bin/env python3
"""
voice_script.py — the recording script, generated from the game.

Every spoken line, with the key it is stored under, in the order it is heard.
The key is the filename to record it as and the field to paste the Roblox asset
id into, so a recording, a slot and a subtitle cannot drift apart.

Writes audio/VOICE_SCRIPT.md and audio/VoiceBank_stub.luau. Run it after adding
or changing a line of dialogue.
"""

import io, os, subprocess, sys, tempfile

ROOT = os.path.join(os.path.dirname(__file__), "..")
os.chdir(ROOT)
LUAU = os.path.join(os.environ.get("LUAU_DIR", "/tmp"), "luau")

# Read the real module rather than re-parsing it: the keys are stamped at load
# time, so the only way to be sure of them is to load it.
dump = r"""
local NS = MODULE()
local out = {}
local function push(group, label, speaker, lines)
	for _, line in lines do
		table.insert(out, table.concat({
			group, label, line.key or "", speaker, tostring(line.seconds or 0),
			(line.text:gsub("\t", " ")),
		}, "\t"))
	end
end

local NIGHTS = {
	{ "Night 1 — First Shift", NS.NIGHT1 },
	{ "Night 2 — The Mannequins", NS.NIGHT2 },
	{ "Night 3 — Night Customers", NS.NIGHT3 },
	{ "Night 4 — Blackout", NS.NIGHT4 },
	{ "Night 5 — Closing", NS.NIGHT5 },
	{ "Endings", NS.ENDING },
}
for _, entry in NIGHTS do
	local fields = {}
	for field in entry[2] do
		table.insert(fields, field)
	end
	table.sort(fields)
	for _, field in fields do
		local lines = entry[2][field]
		local speaker = if field == "calder" or entry[1] == "Endings" then NS.CALDER else NS.MANAGER
		push(entry[1], field, speaker, lines)
	end
end

local tapeNames = {}
for name in NS.TAPES do
	table.insert(tapeNames, name)
end
table.sort(tapeNames)
for _, name in tapeNames do
	local tape = NS.TAPES[name]
	push("Tapes", tape.title, tape.speaker, tape.lines)
end

print(table.concat(out, "\n"))
"""

stub = io.open("tools/roblox_stub.luau", encoding="utf-8").read()
script = io.open("src/shared/NightScript.luau", encoding="utf-8").read()
bundle = stub + "\nlocal function MODULE()\n" + script + "\nend\n" + dump

with tempfile.TemporaryDirectory() as tmp:
    path = os.path.join(tmp, "dump.luau")
    io.open(path, "w", encoding="utf-8").write(bundle)
    result = subprocess.run([LUAU, path], capture_output=True, text=True)
    if result.returncode != 0:
        sys.stderr.write(result.stdout + result.stderr)
        sys.exit(1)

rows = [line.split("\t") for line in result.stdout.strip().split("\n") if line.strip()]

os.makedirs("audio", exist_ok=True)

casting = io.open("src/shared/VoiceBank.luau", encoding="utf-8").read()

md = [
    "# Voice script",
    "",
    "Generated by `tools/voice_script.py`. Do not edit by hand — edit",
    "`src/shared/NightScript.luau` and run the tool again.",
    "",
    f"**{len(rows)} lines.**",
    "",
    "Each line's **key** is three things at once: the filename to record it as,",
    "the field to paste the Roblox asset id into in `src/shared/VoiceBank.luau`,",
    "and the id the subtitle is sent under. Keep them the same and nothing can",
    "drift.",
    "",
    "`seconds` is how long the subtitle holds. A recording longer than that is",
    "fine — the subtitle simply changes while it is still speaking — but a much",
    "longer one will run into the next line, so keep within about a second.",
    "",
    "## Getting a recorded line into the game",
    "",
    "1. **Upload it.** [create.roblox.com](https://create.roblox.com) → Creator",
    "   Dashboard → *Development Items* → *Audio* → *Add Audio*. You can select",
    "   many files at once. Each goes through moderation; speech usually clears",
    "   in a few minutes.",
    "2. **Copy the asset id.** It is the number in the item's URL.",
    "3. **Paste it** into `VoiceBank.IDS` in `src/shared/VoiceBank.luau`, against",
    "   the matching key.",
    "4. Save. Rojo syncs it, and the line speaks the next time it is heard.",
    "",
    "A line with no id plays as a subtitle, which is a supported state — the game",
    "is fully playable with none of this done.",
    "",
    "Press **F9** in game and choose *How much voice is recorded* to see how far",
    "along it is.",
    "",
    "## Casting",
    "",
]

import re

# The notes are written as concatenated string literals over several lines, so
# collect every literal up to the closing brace and join them.
for who, body in re.findall(r'\["?([A-Z\u2014][^"\]]*)"?\] = \{(.*?)\n\t\}', casting, re.S):
    pieces = re.findall(r'"((?:[^"\\]|\\.)*)"', body)
    note = "".join(pieces).replace('\\"', '"')
    md.append(f"**{who}** — {note}")
    md.append("")

group = None
for row in rows:
    g, field, key, speaker, seconds, text = row
    if g != group:
        group = g
        md += ["", f"## {g}", ""]
    md.append(f"- `{key}` · **{speaker}** · {seconds}s")
    md.append(f"  > {text}")

io.open("audio/VOICE_SCRIPT.md", "w", encoding="utf-8").write("\n".join(md) + "\n")

lua = [
    "-- Generated by tools/voice_script.py. Paste your uploaded asset ids in and",
    "-- copy the table into VoiceBank.IDS in src/shared/VoiceBank.luau.",
    "return {",
]
for row in rows:
    lua.append(f"\t{row[2]} = 0, -- {row[3]}: {row[5][:70]}")
lua.append("}")
io.open("audio/VoiceBank_stub.luau", "w", encoding="utf-8").write("\n".join(lua) + "\n")

print(f"{len(rows)} lines -> audio/VOICE_SCRIPT.md, audio/VoiceBank_stub.luau")
